security:
    # Password Hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers
    providers:
        # Use a database provider in production
        database_users:
            entity:
                class: App\Entity\User
                property: username

    # Firewalls
    firewalls:
        # Dev Firewall for Symfony profiler and other dev assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main Firewall for authentication
        main:
            lazy: true
            provider: database_users
            form_login:
                login_path: teacher_login
                check_path: teacher_login_check
                csrf_token_id: authenticate
            logout:
                path: app_logout
                # Optionally, you can add a route to redirect after logout
                # target: homepage

    # Access Control
    access_control:
        # Allow access to the login page without authentication
        - { path: ^/teacher/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Protect the teacher dashboard
        - { path: ^/teacher/dashboard, roles: ROLE_USER }
        # Optionally, you can add more rules for other paths
