security:
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    main:
      pattern: ^/
      form_login:
        login_path: teacher_login
        check_path: teacher_login