# config/packages/security.yaml

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        teachers:
            entity:
                class: App\Entity\Teacher
                property: username

    firewalls:
        main:
            lazy: true
            provider: teachers
            form_login:
                login_path: teacher_login_form
                check_path: teacher_authenticate
                default_target_path: /teacher/dashboard # Redirect here after login
                csrf_token_id: authenticate
            logout:
                path: teacher_logout
                target: teacher_login_form
                invalidate_session: true
                delete_cookies:

    access_control:
        - { path: ^/teacher/authenticate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/teacher/dashboard, roles: ROLE_TEACHER }
        - { path: ^/teacher/account, roles: ROLE_TEACHER }


