controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
teacher_login_form:
    path: /teacher
    controller: App\Controller\TeacherController::loginForm

teacher_authenticate:
    path: /teacher/authenticate
    controller: App\Controller\TeacherController::authenticate
    methods: POST

teacher_dashboard:
    path: /teacher/dashboard
    controller: App\Controller\TeacherController::dashboard
