controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# added here - config/routes.yaml
teacher_login:
  path: /teacher/login
  controller: App\Controller\TeacherController::login
  methods: [POST]

teacher_index:
  path: /teacher
  controller: App\Controller\TeacherController::index
  methods: [GET]