controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# config/routes.yaml
teacher_login_form:
    path: /teacher
    controller: App\Controller\TeacherController::loginForm

teacher_authenticate:
    path: /teacher/authenticate
    controller: App\Controller\TeacherController::authenticate
    methods: POST

teacher_dashboard:
    path: /teacher/dashboard
    controller: App\Controller\TeacherController::dashboard

teacher_account:
    path: /teacher/account
    controller: App\Controller\TeacherController::account

teacher_update_account:
    path: /teacher/update-account
    controller: App\Controller\TeacherController::updateAccount
    methods: POST


#admin route here





admin_create_teacher:
    path: /admin/create-teacher
    controller: App\Controller\AdminController::createTeacher


