controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# Teacher route
teacher_login_form:
    path: /teacher
    controller: App\Controller\TeacherController::loginForm

teacher_authenticate:
    path: /teacher/authenticate
    controller: App\Controller\TeacherController::authenticate
    methods: POST

teacher_dashboard:
    path: /teacher/dashboard
    controller: App\Controller\TeacherController::dashboard

teacher_logout:
    path: /teacher/logout
    controller: App\Controller\TeacherController::logout



teacher_account:
    path: /teacher/account
    controller: App\Controller\TeacherController::account

edit_note:
    path: /teacher/note/{id}/edit
    controller: App\Controller\TeacherController::editNote
    requirements:
        id: '\d+'

delete_note:
    path: /teacher/note/{id}/delete
    controller: App\Controller\TeacherController::deleteNote
    requirements:
        id: '\d+'




#admin route here
admin_login_form:
    path: /admin
    controller: App\Controller\AdminController::loginForm

admin_authenticate:
    path: /admin/authenticate
    controller: App\Controller\AdminController::authenticate
    methods: POST

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

admin_logout:
    path: /admin/logout
    controller: App\Controller\AdminController::logout






admin_create_teacher:
    path: /admin/create-teacher
    controller: App\Controller\AdminController::createTeacher

admin_create_admin:
    path: /admin/create-admin
    controller: App\Controller\AdminController::createAdmin

admin_create_student:
    path: /admin/create-student
    controller: App\Controller\AdminController::createStudent   





#student route here

student_login_form:
    path: /student
    controller: App\Controller\StudentController::index

student_access:
    path: /student/access
    controller: App\Controller\StudentController::access
    methods: POST

student_dashboard:
    path: /student/dashboard
    controller: App\Controller\StudentController::dashboard






#class-teacher here
classteacher_login_form:
    path: /classteacher
    controller: App\Controller\ClassTeacherController::loginform
