controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# Teacher route
teacher_login_form:
    path: /teacher
    controller: App\Controller\TeacherController::loginForm

teacher_authenticate:
    path: /teacher/authenticate
    controller: App\Controller\TeacherController::authenticate
    methods: POST

teacher_dashboard:
    path: /teacher/dashboard
    controller: App\Controller\TeacherController::dashboard

teacher_logout:
    path: /teacher/logout
    controller: App\Controller\TeacherController::logout

teacher_account:
    path: /teacher/account
    controller: App\Controller\TeacherController::account

edit_note:
    path: /teacher/note/{id}/edit
    controller: App\Controller\TeacherController::editNote
    requirements:
        id: '\d+'

delete_note:
    path: /teacher/note/{id}/delete
    controller: App\Controller\TeacherController::deleteNote
    requirements:
        id: '\d+'

teacher_preview_question:
    path: /teacher/preview-question
    controller: App\Controller\TeacherController::previewQuestions

teacher_create_question:
    path: /teacher/create-question
    controller: App\Controller\TeacherController::createQuestion

teacher_get_classrooms:
    path: /teacher/get-classrooms/{teacherSubjectId}
    controller: App\Controller\TeacherController::getClassrooms
    methods: GET

teacher_save_theoryquestion:
    path: /teacher/save-theoryquestion
    controller: App\Controller\TeacherController::saveTheoryQuestion
    methods: POST

update-score:
    path: /teacher/update-score
    controller: App\Controller\TeacherController::updateScore
    methods: [GET, POST, PUT, DELETE, OPTIONS]











#admin route here
admin_login_form:
    path: /admin
    controller: App\Controller\AdminController::loginForm

admin_authenticate:
    path: /admin/authenticate
    controller: App\Controller\AdminController::authenticate
    methods: POST

admin_dashboard:
    path: /admin/dashboard
    controller: App\Controller\AdminController::dashboard

admin_logout:
    path: /admin/logout
    controller: App\Controller\AdminController::logout

admin_list:
    path: /admin/list
    controller: App\Controller\AdminController::listAdmins   

admin_edit:
    path: /admin/edit/{id}
    controller: App\Controller\AdminController::editAdmin
    methods: [GET, POST]

admin_delete:
    path: /admin/delete/{id}
    controller: App\Controller\AdminController::deleteAdmin
    methods: [POST]  # Usually DELETE method, but POST for simplicity

admin_create_admin:
    path: /admin/create-admin
    controller: App\Controller\AdminController::createAdmin

admin_account:
    path: /admin/account
    controller: App\Controller\AdminController::account
    methods: [GET , POST]

admin_message:
    path: /admin/message
    controller: App\Controller\AdminController::message

admin_teacher_list:
    path: /admin/teacher
    controller: App\Controller\AdminController::listTeachers

admin_edit_teacher:
    path: /admin/teacher/edit/{id}
    controller: App\Controller\AdminController::editTeacher
    methods: [GET, POST]

admin_delete_teacher:
    path: /admin/teacher/delete/{id}
    controller: App\Controller\AdminController::deleteTeacher
    methods: [POST]  

admin_create_teacher:
    path: /admin/create-teacher
    controller: App\Controller\AdminController::createTeacher

admin_assign_teacher:
    path: /admin/assign-teacher
    controller: App\Controller\AdminController::assignTeacher

admin_assign_classroom:
  path: /admin/assign-classroom
  controller: App\Controller\AdminController::assignClassroom
  methods: [POST]    

admin_assign_teacher_subject:
  path: /admin/assign-teachersubject
  controller: App\Controller\AdminController::assignTeachersubject
  methods: [POST]    

admin_fetch_teacher_subjects:
  path: /admin/fetch-teachersubjects
  controller: App\Controller\AdminController::fetchTeacherSubjects   

admin_get_all_assignments:
  path: /admin/get-allassignments
  controller: App\Controller\AdminController::getAllAssignments  

admin_delete_assignment:
    path: /admin/delete-assignment/{teacher_subject_id}
    controller: App\Controller\AdminController::deleteAssignment
    methods: POST

admin_assign_classteacher:
    path: /admin/assign-classteacher
    controller: App\Controller\AdminController::assignClassTeacher
    methods: POST

#Message
admin_message_inbox:
    path: /admin/message-inbox
    controller: App\Controller\AdminController::inbox

admin_message_send:
    path: /admin/message-send
    controller: App\Controller\AdminController::sendMessage
    methods: POST

admin_message_fetch:
    path: /admin/message-fetch
    controller: App\Controller\AdminController::fetchMessage

admin_student_list:
    path: /admin/studentlist
    controller: App\Controller\AdminController::studentList

admin_student_edit:
    path: /admin/student/edit/{id}
    controller: App\Controller\AdminController::editStudent

admin_student_delete:
    path: /admin/student/delete/{id}
    controller: App\Controller\AdminController::deleteStudent
    
admin_create_student:
    path: /admin/create-student
    controller: App\Controller\AdminController::createStudent   

admin_curriculum:
    path: /admin/curriculum
    controller: App\Controller\AdminController::curriculumPage

admin_add_classroom:
    path: /admin/add-classroom
    controller: App\Controller\AdminController::addclassroom
    methods: POST

admin_add_subject:
    path: /admin/add-subject
    controller: App\Controller\AdminController::addsubject
    methods: POST

admin_add_department:
    path: /admin/add-department
    controller: App\Controller\AdminController::addDepartment
    methods: POST

admin_add_exam_type:
  path: /admin/add-exam-type
  controller: App\Controller\AdminController::addExamType
  methods: POST

admin_add_session:
  path: /admin/add-session
  controller: App\Controller\AdminController::addSession
  methods: POST

admin_add_term:
  path: /admin/add-term
  controller: App\Controller\AdminController::addTerm
  methods: POST

admin_add_academic_calender:
  path: /admin/add-academic-calender
  controller: App\Controller\AdminController::addAcademicCalender
  methods: [POST]


admin_add_grade:
  path: /admin/add-grade
  controller: App\Controller\AdminController::addGrade
  methods: [POST]

admin_add_exam:
  path: /admin/add-exam
  controller: App\Controller\AdminController::addExam
  methods: [POST]

admin_add_exam_configuration:
  path: /admin/add-exam-configuration
  controller: App\Controller\AdminController::addExamConfiguration
  methods: [POST]

admin_exam_timetable:
  path: /admin/exam-timetable
  controller: App\Controller\AdminController::examTimetable







#student route here

student_login_form:
    path: /student
    controller: App\Controller\StudentController::index

student_access:
    path: /student/access
    controller: App\Controller\StudentController::access
    methods: POST

student_dashboard:
    path: /student/dashboard
    controller: App\Controller\StudentController::dashboard






#class-teacher here
classteacher_login_form:
    path: /classteacher
    controller: App\Controller\ClassTeacherController::loginform



















